### ISSUE TITLE
Suggested correction for wrong Left Threaded Tree delete() method in single_threaded_binary_trees.py

### ISSUE THREAD

**Issue by justyre** [shunsvineyard/forest-python#28]
@shunsvineyard 

Using the following input:

```
tree = LeftThreadedBinaryTree()
tree.insert(key=4, data="")
tree.insert(key=1, data="")
tree.insert(key=7, data="")
tree.insert(key=3, data="")
tree.insert(key=5, data="")
tree.insert(key=8, data="")
tree.insert(key=2, data="")
tree.insert(key=6, data="")
tree.delete(4)
print("After deleting: ")
print(list(tree.reverse_inorder_traverse()))
```

Will give the output:
`[(8, ''), (7, ''), (4, ''), (3, ''), (2, ''), (1, '')]`

Which is clearly incorrect, since the node of key 4 has been deleted.

By comparing with RightThreadedBinaryTree.delete() (which works with no error), I guessed the problem may lie in the Lines 587-591. So I tried deleting ll.587-591 and unindenting ll.592-595, which did give the correct output

`[(8, ''), (7, ''), (6, ''), (5, ''), (3, ''), (2, ''), (1, '')]`

This seems to be a feasible correction. Please check. Thanks!

**Comment by shunsvineyard** [comment]
Thank you for pointing this out. Your suggestion is correct. Since the nodes of the left threaded binary tree do not have right threads, no need to check if the `replacing_node` is a thread or not. Therefore, lines 587-591 are not necessary.
Fixed in the PR https://github.com/shunsvineyard/forest-python/pull/29
